config/routes.rb
Rails.application.routes.draw do



  get 'cars/checkout'
  get 'cars/purchase_complete'
  post 'cars/checkout'

  get 'cars/search'
  post 'cars/search'




  resources :line_items
  resources :carts
  resources :cars
  devise_for :users, controller: {
    registrations: 'registrations'
  }

  get "sign_up",to: "adminregistrations#new"
  post "sign_up",to: "adminregistrations#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in",to: "sessions#new"
  post "sign_in",to: "sessions#create"

  
  
  
  root 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_car(car)
      current_item = line_items.find_by(car_id: car.id)
  
      if current_item
        current_item.increment(:quantity)
      else
        current_item = line_items.build(car_id: car.id)
      end
      current_item
    end
  
    def total_price
      line_items.to_a.sum { |item| item.total_price }
    end
  

    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound,with: :invalid_cart

  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
    begin
    @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to @cart, :notice => 'Invalid Cart'
    else
      respond_to do |format|
        format.html # show.html.erb
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id]=nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "That cart doesn't exist"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Continue Shopping', root_path, class: 'button is-info' %>
</div>
<hr />
<section class="section">
  <%= render(@cart.line_items) %>

  <div class="columns">
    <div class="column">
      <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "button is-danger" %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Total:</span> <%= number_to_human(@cart.total_price) %>
      </h4>
    </div>
  </div>
</section>



<%# unless carts.line_items.empty? %>

<%
=begin%>
 <table>
	<%= render(cart.line_items) %>
	<tr>
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_indian_currency(cart.total_price)  %></td>
	</tr>
</table> 
<%
=end%>
<%# session[:amount] = cart.total_price %>


<%# end %>




<div class="columns is-vcentered">
  <div class="column is-8">
   
  </div>
  <div class="column is-primary">
   	<% if user_signed_in? %>
     
<%= link_to "PLACE ORDER" ,:controller=>"cars",:action=>"checkout", class: 'button is-danger'%>
	<% else %>
	<%= link_to "PLACE ORDER", new_user_session_path %>
	<% end %>

  </div>
</div>