config/routes.rb
Rails.application.routes.draw do



  get 'cars/checkout'
  get 'cars/purchase_complete'
  post 'cars/checkout'

  get 'cars/search'
  post 'cars/search'




  resources :line_items
  resources :carts
  resources :cars
  devise_for :users, controller: {
    registrations: 'registrations'
  }

  get "sign_up",to: "adminregistrations#new"
  post "sign_up",to: "adminregistrations#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in",to: "sessions#new"
  post "sign_in",to: "sessions#create"

  
  
  
  root 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord

  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  has_many :line_items

  mount_uploader :image, ImageUploader
  serialize :image, JSON # If you use SQLite, add this line

  
    validates :title, :brand, :price, :model, presence: true
    validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed. "}
    validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed. "}
    validates :price, length: { maximum: 20 }


  BRAND = %w{ Maruti_Suzuki Hyundai Toyota KIA Mahindra Tata_Motors Tesla BMW  Ferrari  Ford Lamborghini  Audi Bugatti jaguar }
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

  private

  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: [:index, :show]

  # GET /cars or /cars.json
  def index
    

    @cars = Car.all

  #   if session[:admin_id]
  #     @admin =Admin.find_by(id: session[:admin_id])
  #  end

  end




  # GET /cars/1 or /cars/1.json
  def show
    
  end

  # GET /cars/new
  def new
    @car = current_user.cars.build
  end

  # GET /cars/1/edit
  def edit
  end


  def search
    keyword="%" + params[:search].to_s + "%"
    @cars =Car.find_by_sql ["Select * from cars WHERE brand like ? ",keyword]
  end





  def checkout

  	if request.post?

  	amount = session[:amount]
ActiveMerchant::Billing::Base.mode = :test

# Create a new credit card object
credit_card = ActiveMerchant::Billing::CreditCard.new(
  :number     => params[:number],
  :month      => params[:month],
  :year       => params[:year],
  :first_name => params[:first_name],
  :last_name  => params[:last_name],
  :verification_value  => params[:verification_value]
)


if credit_card.valid?
  # Create a gateway object to the TrustCommerce service
  gateway = ActiveMerchant::Billing::TrustCommerceGateway.new(
    :login    => 'TestMerchant',
    :password => 'password'
  )



  # Authorize for $10 dollars (1000 cents)
  response = gateway.authorize(amount.to_i, credit_card)

  if response.success?
    # Capture the money
    #Triger the mailer
    session[:cart]=nil
    gateway.capture(amount.to_i, response.authorization)
    redirect_to :action=>:purchase_complete
  end
  else
    flash[:notice] = "Invalid credit card. Give proper inputs"
    render :action=>:checkout
  end
 end
end



  # POST /cars or /cars.json
  def create
    @car = current_user.cars.build(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      puts "#{params[:id]}yeeeeeeee" 
      @car = Car.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:brand, :model, :description, :condition, :finish, :title, :price,:image)
    end
end

app/helpers/cars_helper.rb
module CarsHelper

    def car_admin(car)
        user_signed_in? && current_user.id == car.user_id 
    end


end

app/views/cars/_car_gallery.html.erb
  <%= form_with url: "/cars/search", local: true, method: :get do |form| %>
  
  <%= form.text_field :search ,class: "input is-medium" %>
  <%= form.submit "Search",class: "button is-active" %>
<% end %>




<div class="instrument-index-grid pt4">
  <% @cars.each do |car| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(car.image_url(:thumb)), car %>
      <% if car.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= car.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to car.title, car %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= car.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_human(car.price) %></p>

      <% if car_admin(car) %>
         <%= link_to 'Edit', edit_car_path(car), class: "button is-small" %>
         <%= link_to 'Delete', car, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/cars/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @car, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 20  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Brand</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Car::BRAND, prompt: "Select brand" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Finish</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :finish, collection: Car::FINISH, prompt: "Select finish" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Condition</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Car::CONDITION, prompt: "Select condition" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input car-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', cars_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/cars/checkout.html.erb
 <span class="f5 has-text-grey">Total:</span> <%= number_to_human(@cart.total_price) %>  <%= session[:amount] %>

<%= form_with do |form| %>


  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

<div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>


  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <%= form.label :date_of_expiry %><br />
      <select name="month" id="check_out_month">
    <option selected value="01">Janurary 
    <option  value="02">Feburary
    <option  value="03">March
    <option  value="04">April 
    <option  value="05">May 
    <option  value="06">June 
    <option  value="07">July 
    <option  value="08">August 
    <option  value="09">September 
    <option  value="10">October 
    <option  value="11">November 
    <option  value="12">December 
    </select>
    <select name="year" id=check_out_year">
    
    <option  value="2021">2021
    <option  value="2022">2022
    <option  value="2023">2023
    <option  value="2024">2024
    <option  value="2025">2025
      <option  value="2026">2026
        <option  value="2027">2027
          <option  value="2028">2028
            <option  value="2029">2029
  </select>

  <div class="field">
    <%= form.label :verification_value %>
    <%= form.text_field :verification_value %>
  </div>

  <div class="actions">
    <%= form.submit "pay"%>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%
=begin%>
 <h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %> 
<%
=end%>


<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing cars
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', car: @car %>
</div>

app/views/cars/index.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Finish</th>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.description %></td>
        <td><%= car.condition %></td>
        <td><%= car.finish %></td>
        <td><%= car.title %></td>
        <td><%= car.price %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %> 
<%
=end%>





<% content_for :header do %>
<section class="navbar is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest Car on sellcar
          
          

      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="instrument-index-grid pt4">
  <% @cars.each do |car| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(car.image_url(:thumb)), car %>
      <% if car.condition? %>
        <div class="condition">
          <span class="tag is-dark"><%= car.condition %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to car.title, car %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= car.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_human(car.price) %></p>

      <% if car_admin(car) %>
         <%= link_to 'Edit', edit_car_path(car), class: "button is-small" %>
         <%= link_to 'Delete', car, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<%
=begin%>
 <h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %> 
<%
=end%>


<% content_for :header do %>
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell Car
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', car: @car %>
</div>

app/views/cars/purchase_complete.html.erb
Thank you for shopping with us!<br />
	
your order has been processed.<br />

A detailed email has been sent.<br />

<a href="/car/index">Click here to continue the shopping</a>

app/views/cars/search.html.erb
<h1>Search results</h1>

<%= render "car_gallery" %>

app/views/cars/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @car.title %></h1>

      <ul class="pv1">
        <% if @car.brand? %>
        <li class="inline-block pr3"><%= @car.brand %></li>
        <% end %>

        <li class="inline-block pr3"><%= @car.model %></li>

        <% if @car.condition? %>
        <li class="inline-block pr3"><%= @car.condition %></li>
        <% end %>
      </ul>

      <div class="feature-image">
        <%= image_tag(@car.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @car.description %>


      <h3 class="subtitle is-4 pt5">Product Specs</h3>

      <table class="table is-narrow">
        <% if @car.condition %>
        <tr>
          <td class="has-text-weight-bold">Condition:</td>
          <td><%= @car.condition %></td>
        </tr>
        <% end %>
        <% if @car.finish %>
          <tr>
            <td class="has-text-weight-bold">Finish:</td>
            <td><%= @car.finish %></td>
          </tr>
        <% end %>
        <% if @car.brand %>
          <tr>
            <td class="has-text-weight-bold">Brand:</td>
            <td><%= @car.brand %></td>
          </tr>
        <% end %>

        <tr>
          <td class="has-text-weight-bold">Model:</td>
          <td><%= @car.model %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_human(@car.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @car.user.name %></p>
        <%= button_to 'Add to cart', line_items_path(car_id: @car), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

  <% if car_admin(@car) %>
    <%= link_to 'Edit', edit_car_path(@car), class: 'button' %>
  <% end %>
</section>