config/routes.rb
Rails.application.routes.draw do



  get 'cars/checkout'
  get 'cars/purchase_complete'
  post 'cars/checkout'

  get 'cars/search'
  post 'cars/search'




  resources :line_items
  resources :carts
  resources :cars
  devise_for :users, controller: {
    registrations: 'registrations'
  }

  get "sign_up",to: "adminregistrations#new"
  post "sign_up",to: "adminregistrations#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in",to: "sessions#new"
  post "sign_in",to: "sessions#create"

  
  
  
  root 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SellOldCar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= yield (:body_class) %>">

   <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
        </div>
     <%end %>


   <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
        </div>
     <%end %>

     <nav class="navbar is-primary" role="navigation"  aria-label="main navigation ">
       <div class="navbar-brand">
          <%= link_to root_path , class: "navbar-item" do %>
             <h1 class="title is-5">SellOldCar </h1>

          <% end %>  

          <div class="navbar-burger burger" data-target="navbar">
             <span> </span>
              <span> </span>
               <span> </span>

            </div>
            </div>

        <div id="navbar" class="navbar-menu">
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                  
                  
                <% if total_cart_items %>
                     <%= link_to  cart_path(@cart), class:"navbar-item button is-info is-rounded" do %>
                     <span class="icon is-small">
                       <i class="fa fa-shopping-cart"> </i>
                       </span>
                       <span>cart
                          <%= cart_count_over_one%>
                        </span>
                     <%end %>
                    <%end %> 




                  <% if user_signed_in? %>
                     <%= link_to 'Add car to Sell',new_car_path , class:"navbar-item button is-link is-rounded"%>
                       
                       <div class="navbar-item has-dropdown is-hoverable">
                          <%= link_to 'Account Setting', edit_user_registration_path, class:"navbar-link  is-rounded " %> 
                         <div class="navbar-dropdown is-right">
                                <%=link_to current_user.email ,edit_user_registration_path ,class:"navbar-item" %>
                                <%=link_to 'LogoutAdmin',destroy_user_session_path,method: :delete , class:"navbar-item" %>  

                          </div>
                          </div>

                          <% else %>
                                <%=link_to 'Sign up Admin ',new_user_registration_path ,class:"navbar-item button is-info " %> 

                                <%=link_to 'Sign In Admin',new_user_session_path ,class:"navbar-item button is-warning" %>   
                          <% end %>   




     <% if @admin %>
        
            <span> <%= @admin.email%></span>
          
           
          <%= button_to "LogOut User", logout_path, method: :delete,class:"navbar-item button is-info" %>
         
      <% else %>
  
          <%= link_to "Sign Up As User ", sign_up_path,class:"navbar-item button is-info" %>
       
          
             <%= link_to "Login  As User", sign_in_path ,class:"navbar-item button is-warning" %>
         
      <% end %>






                          </div>
                          </div>
                          </div>
                          </div>
                          </nav>    






    





    <%= yield(:header) %>

    <div class="container">
        <%= yield %>

      </div>







<footer class="footer">
  <div class="content has-text-centered">
    <p>

    Legal Disclaimer | Sitemap | Career | FAQ | Contact Us
Copyright 2021 Cars Motor India. All Rights Reserved.
      <strong></strong>  <a href="https://jgthms.com"></a>.
      <a href="http://opensource.org/licenses/mit-license.php"></a>. 
      <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/"></a>.
    </p>
  </div>
</footer>

  </body>
</html>